Card Layout, ListView, GridView, Togglebutton 까지 구현 완료 !
MentalJava/hotel-reservation pull request #9
Opened 2024-07-10 04:14 UTC by MentalJava

Card Layout UI와 ListView GridView 를 볼 수 있는 ToggleButton 까지 완성 했습니다 ! 

Obx로 상태관리 진행하였습니다 !

Hotel List 추가 예정

2024-07-10 06:36 UTC, kdjun97 requested changes
사진 여러개 케이스 + 카드에 있는 우측 하단 버튼 수정 필요할 것 같습니다. @MentalJava

2024-07-10 06:36 UTC, kdjun97 commented on lib/screens/home.dart
> +                return viewToggleController.isGridView.value
Rayout typo @MentalJava

2024-07-11 01:28 UTC, kdjun97 requested changes
Model 을 생성해서 모델을 넘기는 쪽으로 CardView 구현을 고려하면 더 좋을 것 같아요!

2024-07-11 01:28 UTC, kdjun97 commented on lib/controllers/view_toggle_controller.dart
> +
네이밍이 어색합니다 @MentalJava

2024-07-11 01:28 UTC, kdjun97 commented on lib/widgets/card_rayout/build_card.dart
> +                  children: [
숫자를 받아와서 별을 처리하면 더 좋을 것 같네요 @MentalJava

2024-07-11 16:07 UTC, MentalJava commented on lib/screens/home.dart
> +                return viewToggleController.isGridView.value
수정 완료 ! @kdjun97

2024-07-11 16:07 UTC, MentalJava commented on lib/controllers/view_toggle_controller.dart
> +
수정 완료했습니다 ! @kdjun97

2024-07-11 16:08 UTC, MentalJava commented on lib/widgets/card_rayout/build_card.dart
> +                  children: [
구현 완료 했습니다 ! @kdjun97

2024-07-12 01:38 UTC, kdjun97 approved these changes
좋습니다.

수정 요구 사항들을 잘 파악해서 알맞게 잘 고치셨네요.
이 프로젝트도 끝자락이 보입니다. 조금만 더 힘 냅시다! @MentalJava 👍

2024-07-12 01:38 UTC, kdjun97 commented on lib/controllers/view_toggle_controller.dart
> +
cool! 👍 @MentalJava

2024-07-12 01:38 UTC, kdjun97 commented on lib/models/hotel_list_model.dart
> +
호텔 모델 아주 좋아요~ @MentalJava 👍

2024-07-12 01:38 UTC, kdjun97 commented on lib/models/hotel_list.dart
> +class HotelList {
이렇게 들고 있는거 아주 좋아요~~ @MentalJava 💯

2024-07-12 01:38 UTC, kdjun97 commented on lib/widgets/card_layout/list_card.dart
> +              child: Image.asset(
static 을 활용하면 HotelList 생성 없이 class 내부 프로퍼티를 사용할 수 있습니다~ @MentalJava

2024-07-12 02:44 UTC, merged

2024-07-12 02:50 UTC, MentalJava commented on lib/widgets/card_layout/list_card.dart
> +              child: Image.asset(
확인했습니다 바로 수정하겠습니다!  @kdjun97